### ISSUE TITLE
Anchors to questions in FAQ don't include header

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-docs#212]
This how things look after opening a certain FAQ anchor:

![Selección_062](https://user-images.githubusercontent.com/365293/102104848-a5f0b280-3dfc-11eb-88ef-22fc9590b308.png)

However, I think that looks odd and I'd really prefer that the header would be shown too, like this:

![Selección_063](https://user-images.githubusercontent.com/365293/102105027-e05a4f80-3dfc-11eb-99ea-550086f6bc60.png)

@CAM-Gerlach, could you take care of this? Thanks!

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Could you please describe the browser, OS and exact steps to reproduce? Most of the code, complexity and commits in PR #207 is dedicated to avoiding this very issue, and as part of that PR, I successfully tested this specific behavior extensively across FF and Chrome on both Windows and Android in a variety of situations (and asked you and @juanis2112 to do the same on your platforms as part of your review).

The only scenario I had found (which my restesting now confirms) that behaved in an undesired fashion as in your above screenshot, which I mentioned on both the PR and in the meeting, was if a user clicked the direct link button on an FAQ question again immediately after already clicking it once, or after the page had already been opened to the same question without clicking any other button in between. This is because the browser's built-in anchor scroll functionality is triggered, but it doesn't actually fire an anchor changed event (which is what triggers our custom JS) because the id anchor doesn't change.

I believe it should be possible to avoid this by adding our own custom event handler to the direct link buttons that fires whenever they are clicked regardless of whether the anchor changes and hacks around the core browser behavior, but as there isn't a clear reason why an average user (as opposed to one of us) would intentionally click the link button again on the the same question that's already open and scrolled to, I'm not sure its worth the time, complexity and bug potential that additional potentially tricky overriding of built-in behavior (that varies between browsers and platforms) would require. However, if it can be reproduced in another realistic scenario, then I can certainly take a look, so please let me know.

**Comment by ccordoba12** [comment]
> @ccordoba12 Could you please describe the browser, OS and exact steps to reproduce?

Firefox 78 on Linux.

> The only scenario I had found (which my restesting now confirms) that behaved in an undesired fashion as in your above screenshot, which I believe I mentioned on both the PR and in the meeting, was if a user clicked the direct link button on an FAQ question again immediately after already clicking it once, or after the page had already been opened to the same question without clicking any other button in between. 

In my case this happens every time I click on an anchor.

**Comment by CAM-Gerlach** [comment]
Okay, thanks. I cannot reproduce this behavior on FF 80 and Chrome 87 on Windows 8.1, nor on Falkon 3.0.0, QtWebEngine 5.10.1 or FF 83 on my own Linux VM (Fedora 29 LXQt). However, I _can_ reproduce it some of the time on FF 78 on my Linux VM when clicking on , seemingly at random, which suggests to me its likely a race condition between the built-in browser functionality that scrolls to anchors and my code (which I had added mitigations for which worked on all the systems I tested, but evidently they didn't go far enough for everything, which is why I wanted to make sure it was tested across a variety of browsers and platforms before behind merged). I'll set up a docs dev environment on my VM and see what I can do to fix this.

**Comment by ccordoba12** [comment]
> I'll set up a docs dev environment on my VM and see what I can do to fix this.

Thanks, but if this caused by an old browser, I think we can simply close it (I just haven't had time to update my distro).

I thought this was a general (and really bad) problem, but if it's working in newer versions, I see no reason to invest more time on it.

**Comment by ccordoba12** [comment]
Closing because I verified this is not a problem in Firefox 84 on Linux.
