### ISSUE TITLE
Mention the limit of saved lines in the History pane

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-docs#252]
# Issue Report

## Issue Description

The current limit is 1000 lines but we are mentioning that at the moment. This issue was prompted by the following SO question:

https://stackoverflow.com/questions/67526826/clear-history-tab-of-ipython-console

### Where is the relevant portion of the documentation located?

http://docs.spyder-ide.org/current/panes/historylog.html

### What would you suggest it be replaced with?

We should mention the limit on that section and that it's not possible to change it.

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

    Let's make this change for both Spyder 4 and 5.

* Are you planning on submitting a Github pull request with a suitable change?

    No. @juanis2112, please take care of this one.

**Comment by ccordoba12** [comment]
We should also mention that History can't be cleared up (another suggestion from that question).

**Comment by CAM-Gerlach** [comment]
Given this issue has been inactive for months, I've gone ahead with a PR to solve it.

Somewhat OT, but only 1000 lines seems awfuly short, considering (unfortunately) many scientific scripts are much longer than that. Even with over 1000 lines, most of them long, my history log is a minuscule 30 kB (around 0.1% of the 2-5 MB size of the variety of current, dev and backup `.spyder-py3` dirs I have sitting around, and around 0.0001% of the hundreds of megabytes installed by the Spyder installers), and only covers a small portion of my total useful history. Since its hard-coded, wouldn't it make sense to bump it to a more reasonable 10 000 lines instead?

Also, a clear command in the options menu would seem to be of some utility, for users who want to start fresh without the clutter of previous sessions, if the user exposed sensitive credentials in clear text, etc, but is probably less trivial to implement, and given limited user demand (a couple related issues and this SO post) not sure if its worth making a bug report over.

**Comment by CAM-Gerlach** [comment]
Closing manually since auto-closed got confused due to "issue" separating "fix" and the number.
