### ISSUE TITLE
Quickstart displaying Spyder 5 mainwindow screenshot in Spyder 4 docs

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder-docs#268]
# Issue Report

## Issue Description

Quickstart is displaying  screenshot of Spyder 5  in spyder4 docs

<img width="1440" alt="Screenshot 2021-07-14 at 7 11 17 PM" src="https://user-images.githubusercontent.com/18587879/125708462-43ca6ffb-3ab5-4932-8fe1-4f068cf804b9.png">

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

* Are you planning on submitting a Github pull request with a suitable change?

* Anything else you'd like to add?

**Comment by CAM-Gerlach** [comment]
This is presumably due to how the URL of the image to load is retrieved; we should be able to fix this by using relative URLs, or failing that, just hardcoding them. Should be a simple fix.

**Comment by CAM-Gerlach** [comment]
It looks like that was all correct; the issue was that apparently `sphinx-mutliversion` always uses the build branch's (i.e. `master`) `_static` directory, which allows the different versions of the site to stay in sync in terms of overall appearance and menus, top bar, etc., but since the tour images are in `doc/_static/images` instead of `doc/images`, they are copied too. I'll open a PR to move them, which should fix it, so long as they don't need to be in `_static` for other reasons. However, this also means that given the `javascript` code is in `_static`, which in turn contains the our step data, this also will be mirrored between versions, so if we want to make major changes to the text or add more, we'll need to e.g. move that to a JSON inside the docs directory and load that in the JS.

**Comment by CAM-Gerlach** [comment]
Solving this is ending up being much more complicated than anticipated due to Sphinx-Multiversion copying both static and extra dirs from the build branch, not the current branch, regardless of the current settings, and including them in `images` doesn't work either, as they apparently aren't copied at all if they aren't used. I believe we may be able to work around this by just including both in separate subdirectories of an extra/static-specified dir and then hardcoding the version paths. Annoying, but every other way I can think of around this that I haven't tried is much more hacky and fragile, and while moderately duplicative on the server, it shouldn't take up any extra space in the Git repo.

**Comment by CAM-Gerlach** [comment]
Confirmed fixed now. The same strategy can be used if and when we want to use unique steps/step descriptions, coupled with storing these data in a JSON files in a versioned subdir of assets, coupled with making a call to the quickstart trigger code including the versioned data path to load into an inline `<script>` block inside the raw directive in the quickstart source files, so it loads the version-specific data (will take a bit of work, so deferring for now until it is needed). @juanis2112 , if you want to add Spyder 5-only text or steps to the tour, please let me know so I can implement the above first. Thanks.
