### ISSUE TITLE
How to install package after using standalone installers of spyder

### ISSUE THREAD

**Issue by yucheng90** [spyder-ide/spyder-docs#334]
## Problem Description
I installed spyder(4.2.0) by using standalone installers. I saw there is a folder 'pkgs' which contains all packages from standalone installers. How can I install new or update current packages? It seems there is no prompt or pip installed.

## Versions
* Spyder version: 4.2.0
* Python version: 3.7.9
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: window7

**Comment by CAM-Gerlach** [comment]
Thanks for the great detailed feedback and suggestions, everyone—they were very helpful us revise our docs to make sure we cover all the bases.

In PR #335, I've expanded, updated and rewritten most of the Installation Guide guidance surrounding standalone installers and Anaconda/Miniconda, to address this feedback and reflect the current situation more accurately, as well as make other smaller related improvements. Please let us know if it helps address this issue, and if you have further suggestions to improve it. Thanks!

I'm not sure about adding a whole UI dialog in Spyder, especially since our new experimental installers will support all of this (Linux, plugins, environment and package management, etc) directly, but we can also add a note on the download section of the website.

**Comment by CAM-Gerlach** [comment]
FYI, I've opened spyder-ide/website-spyder#210 to update the language of the Download section on the Spyder website to reflect these concerns, and further revised the other Install Guide sections in the aforementioned PR to ensure they are more helpful, complete and up to date.

**Comment by benkinooby** [comment]
Thanks @CAM-Gerlach for the quick reaction and fixes in https://github.com/spyder-ide/spyder-docs/pull/335 and https://github.com/spyder-ide/website-spyder/pull/210

For what it is worth: I had a quick look at the diffs and the changes certainly look like an improvement to me! They expand on the trade-offs between the different installation methods and make clear that Spyder comes with its own python environment in the standalone installation (and why).

I am not the one who opened this issue, but from my point of view, the PRs linked would be sufficient to close this issue.

**Comment by CAM-Gerlach** [comment]
Thanks for your kind feedback @benkinooby ! I'm glad it seems helpful to you!
