### ISSUE TITLE
Clicking some links blocked by invisible hN::before element from the theme

### ISSUE THREAD

**Issue by D1dymu2** [spyder-ide/spyder-docs#350]
# Issue Report
Welcome Page  - partially flawed hyper link

## Issue Description

Thank you for the link to the Spyder documentation source code.
    
https://docs.spyder-ide.org/current/index.html
Welcome Page
`docs contributing guide`_ link 
Only the "docs" part of the "docs contributing guide" hyper link appears active.

If you move the mouse pointer past the "s" in "docs" to the space and all the letters beyond this the link seems to fail, is no longer a hyper link.

Tested on Browsers:
Google Chrome:   Version 114.0.5735.199 (Official Build) (64-bit)
Firefox:                  Version 102.13.0esr (64-bit)

### Where is the relevant portion of the documentation located?

I am learning the Sphinx documentation tool and the rST markup language

Welcome Page https://docs.spyder-ide.org/current/index.html
`docs contributing guide`_ link 
Only the "docs" part of the "docs contributing guide" hyper link works.

### What would you suggest it be replaced with?

I cannot answer this.  This may be something with a Browser or Sphinx interpreted issue.   I am not sure.

### Other information

* Is the problem specific to documentation for a particular version of Spyder?

    * [ ] N/A
    * [x] Spyder 5 (``master``)
    * [x] Spyder 4 (``4.x``)
    * [ ] Spyder 3 (``3.x``, frozen)

* Are you planning on submitting a Github pull request with a suitable change?

    * [ ] Yes
    * [x] No
    * [ ] Maybe so

**Comment by D1dymu2** [comment]
No problem at all.  Would you be able to inform me of the solution, please?

Best wishes,
Tommy.

**Comment by CAM-Gerlach** [comment]
Thanks for the detailed report! I actually analyzed this in detail a couple months ago and typed up a response, but I didn't realize I'd never actually hit submit, sorry.

To make a long story short, I could reproduce it at viewport widths greater than the 1200 px breakpoint, and tested and eliminated a bunch of things it wasn't, including anything specific to that link in the DOM, the HTML and in the reST source from any other on the page, as well as any CSS or JS that is getting applied to it or any of its parent elements, or any `@media` queries specific to that breakpoint.

However, after some more testing now, I found the culprit: its due to an invisible pseudo-element (the `::before` from the `h3`s) extending into part of the space of the previous sections at certain widths and locations, covering up parts (or in some cases, all) of the links before them and rendering them unclickable.

While I have a few hypotheses I'm not entirely certain why its there, but since we're replacing our docs theme in the next couple months anyway, I've opened PR #354 that applies a quick CSS fix to make the invisible element not block clicks. Thanks!
