### ISSUE TITLE
Broken link to unstable Debian package in installation instructions

### ISSUE THREAD

**Issue by sirredbeard** [spyder-ide/spyder-docs#46]
## Issue Description

Link to unstable Debian package in install instructions is broken.

Link at end of "The Spyder’s official Debian package is available here" on https://pythonhosted.org/spyder/installation.html.

Is http://packages.debian.org/fr/sid/spyder. Should be https://packages.debian.org/unstable/spyder.

Link is broken. Also sid will not always be unstable.

**Comment by CAM-Gerlach** [comment]
Thanks @sirredbeard ! This is already fixed in #44 , which will hopefully be green to merge shortly, I did incorporate your suggestion regarding ``sid`` vs. ``unstable`` ; thanks for the catch! I also switched the package name to ``spyder3`` as I was unaware the default ``spyder`` package was Python 2. Again, really appreciate it, and keep those bugfixes coming (though I'd advise you to wait until after #44 is merged since a vast number of issues have been fixed there).

Also, just FYI as you're probably aware, our docs on PythonHosted are way out of date (as its frozen), so very shortly we will be officially switching them to our new docs.spyder-ide.org subdomain (they've already been live for some time; we're just finishing up a major overhaul before officially releasing them; that's what the I.P.R. milestone's all about).
