### ISSUE TITLE
Basic documentation for Spyder plugins

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-docs#88]
@goanpeca commented on [Wed Jan 20 2016](https://github.com/spyder-ide/spyder/issues/2944)

---

@Nodd commented on [Tue Jun 21 2016](https://github.com/spyder-ide/spyder/issues/2944#issuecomment-227441014)

Added some docs:
https://github.com/spyder-ide/spyder/wiki/User-plugins
https://github.com/spyder-ide/spyder/wiki/Writing-Plugins
It's very basic and inspired from the old googlecode site: http://web.archive.org/web/20141228215028/https://code.google.com/p/spyderlib/wiki/SpyderPlugins

---

@ccordoba12 commented on [Tue Jun 21 2016](https://github.com/spyder-ide/spyder/issues/2944#issuecomment-227487692)

Thanks @Nodd!!

---

@ccordoba12 commented on [Sun Aug 13 2017](https://github.com/spyder-ide/spyder/issues/2944#issuecomment-322059899)

This can be improved once we merge the `split-plugins` branch.

---

@ccordoba12 commented on [Fri Oct 12 2018](https://github.com/spyder-ide/spyder/issues/2944#issuecomment-429463540)

Moving to spyder-docs.

**Comment by CAM-Gerlach** [comment]
Thanks @ccordoba12 . I can add a new doc with the existing contents of User Plugins page (since these docs are aimed at all users, while our wiki more for developing Spyder itself), bring it up to standards and flesh it out at least to a baseline degree, and we can go from there. This will of course be in ``master``, since we are mainly focused on supporting plugins in Spyder 4 and they aren't fully maintained right now so we don't need to advertise them on the live ``3.x`` docs.

**Comment by ccordoba12** [comment]
> This will of course be in master

Sure, that's fine.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 @juanis2112 Documenting the plugin API is being done in a separate repo (the original topic of this issue) and the officially supported first-party plugins are already or in the final stages of being documented here, so we can close this one, right?

**Comment by CAM-Gerlach** [comment]
Given its been seven days, I'll go ahead and close this. If there are further plugins that should be documented, we can open separate issues about them.
